### ISSUE TITLE
explanation of metadata in atlas

### ISSUE THREAD

**Issue by LisaSikkema** [davemcg/massive_integrated_eye_scRNA#17]
Hi! 

Thank you for having created this atlas, I really like your work!

I have a few questions about the metadata in the scanpy .h5ad object that I downloaded from the link in your readme. In particular, I'm wondering which covariate you used for your scANVI integration. In the paper I read the following:
>We define "batch" as each unique biological sample and assume that each study is ≥1 unique sample. We studied the metadata and methods of each study to identify the unique biological samples. Within the current scEiaD dataset we identified 86 batches across 33 deposited datasets in 26 published articles.

None of the numbers in the atlas I downloaded line up with these numbers though, maybe because you have expanded the atlas since?

Either way, my questions are:
- where can I find your batch covariate in the data?
- what do the covariates `batch`and `Batch` represent (/what's the difference)? And what's `Covariate.x`?
- where can I find donor information (i.e from which patient/donor/mouse each sample came)? `Donor.X` has only 7 unique values, so I'm guessing that's not it?
- what's the difference between `biosample_title.x`, `biosample.x` and `sample_accession.x`? They have a different number of unique values. Same for `biosample.x` versus `biosample.y` etc. Which one should I use if I want to know the biological sample each cell came from?
- am I correct to assume that all the data in the atlas comes from healthy/control samples?

Thanks a lot for your help!

**Comment by davemcg** [comment]
Apologies for the delay...I didn't get (or notice) a notification for your issue. 

1. The batch covariate for scANVI (used for the current release: https://tvst.arvojournals.org/article.aspx?articleid=2792870) is, apparently, "study_accession" 
  - https://github.com/davemcg/scEiaD/blob/master/config.yaml (line 28)
  - I did test/try "batch" also but apparently it must have not made much of a difference so I ended up doing the simpler thing
2. everyone is healthy/control
3. The h5ad is a byproduct of the processing pipeline (I'm an R shop) and it appears that the join to add the metadata has caused some duplicates (hence the .x and .y fields)
  - the safest thing to do is to pull the [cell level metadata](http://hpc.nih.gov/~mcgaugheyd/scEiaD/2022_03_22/metadata_filter.tsv.gz) and re-join to the h5ad via the "Barcode" field (which is unique to each cell by adding the sample_accession to each barcode).
4. The "batch" field in the core metadata is essentially me glomming on, not super consistently, sample level information onto the study accession (and scRNA tech). People are not consistent with using sample_accession with actual biological samples....hence me trying to read papers and interpret their metadata fields.
5. biosample_title/biosample/sample_accession comes from GEO/SRA
6. The "donor" info is best taken from either the sample_accession (which again sometimes is wrong) or the "batch" field (which is hand-curated...but no guarantees I did it right). This basically is substantially more annoying than you'd expect.


Happy to discuss this further - I can also (maybe?) provide scVI/scANVI objects. Though those are likely tricky to use as I last ran scVI/scANVI before they had fully worked out the "how to reliably share a model with someone else" engineering.

**Comment by davemcg** [comment]
Expanding a bit on the "sample_accession" / "batch" messiness: 

1. People don't reliably label their biological samples with a unique sample_accession
2. So you can get several, mice/whatever, with the same ID sometimes
3. BUT ALSO sometimes people will take a single sample and give it like four different sample_accessions because the same sample got sequenced across four machines. 
4. In the previous case I would consider that "one sample" and thus the "batch" field was my attempt to try and understand what the researchers were actually doing

**Comment by LisaSikkema** [comment]
HI @davemcg , thanks a lot for your response, very helpful :) 
And I know the pain of cleaning up metadata, we had the same issues for the human lung cell atlas and it was long and tedious work..
I didn't realize your scANVI model wasn't public yet, and yes it would be great if you could share it! When did you run it last? There are actually ways to update these to the latest format, so hoping it will be doable to share and reuse

**Comment by davemcg** [comment]
The scANVI model pieces:

  - [hpc.nih.gov/~mcgaugheyd/scEiaD/2022_03_22/scANVI_model/adata.h5ad]()
  - [hpc.nih.gov/~mcgaugheyd/scEiaD/2022_03_22/scANVI_model/model.pt]()
  - [hpc.nih.gov/~mcgaugheyd/scEiaD/2022_03_22/scANVI_model/adata.h5ad.gz]() (uh maybe just the h5ad that I manually zipped?)

Run with scvi 0.15.2

**Comment by LisaSikkema** [comment]
Thanks a lot!
